### ISSUE TITLE
Lack of updated source code

### ISSUE THREAD

**Issue by Tichy** [MeteoricGames/pioneer#339]
I see that Paragon/Jumpdrive is constantly updated on Steam, but I see no source updates here on GitHub.

Since Paragon/Jumpdrive is a fork of GPL3 game Pioneer ( https://github.com/pioneerspacesim/pioneer/ ), that source should be made available.

**Comment by Adelxoxo** [comment]
Will be updated tonight sorry about that.

**Comment by fluffyfreak** [comment]
@Adelxoxo thanks :)

**Comment by justinbowes** [comment]
Should this be reopened, or should we create a new issue?

**Comment by fluffyfreak** [comment]
@justinbowes totally up to you. We're pretty relaxed about the way @lionhearted et al do the releasing of the updates. It's never a priority when you've got deadlines and work to do on a game, but it has been quite a long time since the last dump.

Perhaps a new issue to track it?
